name: CI/CD Pipeline - Node App to AWS ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: yemmy-node-project
  ECS_CLUSTER: my-ecs-cluster
  ECS_SERVICE: yemmy-node-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials (OIDC)
      # ODIC is an auth standard allowing github prove its access to AWS without using PAT
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::930758456167:role/GitHubActionsECSRole
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build, tag, and push Docker image
      - name: Build and push Docker image to ECR
        id: build-image
        run: |
          IMAGE_TAG=${{ github.run_id }}
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

          echo "Building Docker image..."
          docker build -t $IMAGE_URI .

          echo "Pushing image to ECR..."
          docker push $IMAGE_URI

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Step 5: Update ECS task definition with new image
      # This is needed because only a placeholder image was created during setting up ECS task definition
      - name: Update ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          container-name: yemmy-node-container
          image: ${{ env.IMAGE_URI }}

      # Step 6: Deploy new task definition to ECS
      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
